version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wgforge
      MYSQL_DATABASE: wgdb
      MYSQL_PASSWORD: wgforge
